### PR TITLE
random_seed: on error, continue to next method

### PR DESCRIPTION
**Pull request by ploxiln**
instead of exiting the process

fixes https://github.com/json-c/json-c/issues/672

### CODE REVIEW

**Comment by ploxiln** [comment]
https://travis-ci.org/github/json-c/json-c/builds/733556076 (passed, didn't post status here, dunno why)

**Comment by ploxiln** [comment]
I could change these functions from "return 0 on success or -1 on error" to "return 1 on success or 0 on error", if there's a preference.

**Review by qlyoung — APPROVED** [review]
LGTM, thank you! @hawicz can you please review this?

**Review by dota17 — APPROVED** [review]
LGTM

**Comment by qlyoung** [comment]
Is this library unmaintained?

**Comment by hawicz** [comment]
It is maintained, I just haven't had a whole lot of time lately to look at issues here.
Anyway, this looks fine to merge, so I'm doing so.

**Pull request merged**
