### PR TITLE
Support to build both static and shared libraries

### PR DESCRIPTION
**Pull request by dota17**
#593

### CODE REVIEW

**Comment by dota17** [comment]
Allow to build both static and shared libraries.

```sh
cmake -DBUILD_STATIC_LIBS=ON ..
```

**Comment by hawicz** [comment]
We should default to both static and shared being built, and describe `-DBUILD_SHARED_LIBS=OFF` and `-DBUILD_STATIC_LIBS=OFF` as simply turning the relevant build off, rather than having it say it turns the "other" libs build on.

**Comment by dota17** [comment]
ok

**Comment by hofnarrr** [comment]
Hi, there is some problems with the fix this branch provides. Not sure what's the "correct" way to submit fixes to other people's PR's, so I submitted a pull request to dota17's branch (https://github.com/dota17/json-c/pull/90).

**Comment by dota17** [comment]
@hofnarrr  Thanks a lot! I found the install error of share&static libraries  before and was thinking how to fix it. ha-ha.

**Pull request merged**
