### PR TITLE
Bump so-name and improve CMake

### PR DESCRIPTION
**Pull request by besser82**
As stated in the individual commit messages.

### CODE REVIEW

**Comment by ploxiln** [comment]
I think that a feature addition typically merits an so minor bump. You said there were also backwards-incompatible ABI changes - it is probably worth mentioning at least one one significant example.

It is probably also worth adding a comment to the commit and to the cmake config about what CMP0075 is.

**Comment by hawicz** [comment]
Also, as of https://github.com/json-c/json-c/blob/11a638048da0344a3bd5f38722ddecdf5ec22041/CMakeLists.txt I've included the VERSION and SOVERSION properties.

**Comment by hawicz** [comment]
If I'm understanding CMP0075 correctly, it would make the target_link_libraries lines in tests/CMakeLists.txt irrelevant, no?

**Comment by hawicz** [comment]
Not merging, since two of the changes have been made independently, and it's not clear that the library version needs to be bumped.

**Pull request closed without merging**
