### PR TITLE
Fix Win32 build problems

### PR DESCRIPTION
**Pull request by sixlettervariables**
Michael,

I've had a few emails in the past months about build failures on Windows. This PR should fix them for most newer VS versions. I don't have versions older than 2012 with which to confirm.

- Updates config.h.win32 to match config.h.in (I tried my best to get the `PACKAGE_*` details correct)
- Adds json_config.h.win32
- Adds include required for `InterlockedCompareExchange` in linkhash.c
- Updates old VS project to copy json_config.h.win32 to json_config.h
- Adds VS2k13 project

The project now builds, although with numerous warnings about "insecure" API's. Let me know if you'd like me to push a commit which adds `_CRT_SECURE_NO_DEPRECATE` to suppress these warnings.

### CODE REVIEW

**Comment by Nzbuu** [comment]
Works for me in Visual Studio 2013, but not in Visual Studio 2010 or against Windows SDK 7.1. Log attached.

```
1>------ Rebuild All started: Project: json-c, Configuration: Debug Win32 ------
1>          1 file(s) copied.
1>          1 file(s) copied.
1>  printbuf.c
1>~\src\printbuf.c(142): warning C4996: 'vsprintf': This function or variable may be unsafe. Consider using vsprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(371) : see declaration of 'vsprintf'
1>~\src\printbuf.c(162): warning C4996: '_vsnprintf': This function or variable may be unsafe. Consider using _vsnprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(363) : see declaration of '_vsnprintf'
1>  linkhash.c
1>~\src\linkhash.c(237): error C2061: syntax error : identifier 'hashlittle'
1>~\src\linkhash.c(237): error C2059: syntax error : ';'
1>~\src\linkhash.c(237): error C2059: syntax error : 'type'
1>~\src\linkhash.c(423): warning C4013: 'hashlittle' undefined; assuming extern returning int
1>  json_util.c
1>~\src\json_util.c(74): warning C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\io.h(235) : see declaration of '_open'
1>~\src\json_util.c(76): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\string.h(157) : see declaration of 'strerror'
1>~\src\json_util.c(80): warning C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _close. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\io.h(302) : see declaration of 'close'
1>~\src\json_util.c(84): warning C4996: 'read': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _read. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\io.h(313) : see declaration of 'read'
1>~\src\json_util.c(87): warning C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _close. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\io.h(302) : see declaration of 'close'
1>~\src\json_util.c(90): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\string.h(157) : see declaration of 'strerror'
1>~\src\json_util.c(112): warning C4996: '_open': This function or variable may be unsafe. Consider using _sopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\io.h(235) : see declaration of '_open'
1>~\src\json_util.c(114): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\string.h(157) : see declaration of 'strerror'
1>~\src\json_util.c(119): warning C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _close. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\io.h(302) : see declaration of 'close'
1>~\src\json_util.c(126): warning C4996: 'write': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _write. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\io.h(318) : see declaration of 'write'
1>~\src\json_util.c(127): warning C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _close. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\io.h(302) : see declaration of 'close'
1>~\src\json_util.c(129): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\string.h(157) : see declaration of 'strerror'
1>~\src\json_util.c(137): warning C4996: 'close': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _close. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\io.h(302) : see declaration of 'close'
1>~\src\json_util.c(150): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(325) : see declaration of 'sscanf'
1>~\src\json_util.c(163): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(325) : see declaration of 'sscanf'
1>~\src\json_util.c(167): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(325) : see declaration of 'sscanf'
1>~\src\json_util.c(197): warning C4996: 'sscanf': This function or variable may be unsafe. Consider using sscanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(325) : see declaration of 'sscanf'
1>~\src\json_util.c(226): warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(363) : see declaration of '_snprintf'
1>  json_tokener.c
1>~\src\json_tokener.c(241): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\string.h(238) : see declaration of 'strdup'
1>~\src\json_tokener.c(361): error C2143: syntax error : missing ';' before 'type'
1>~\src\json_tokener.c(362): error C2065: 'infbuf' : undeclared identifier
1>~\src\json_tokener.c(362): error C2100: illegal indirection
1>~\src\json_tokener.c(364): error C2065: 'infbuf' : undeclared identifier
1>~\src\json_tokener.c(368): warning C4013: 'strncasecmp' undefined; assuming extern returning int
1>~\src\json_tokener.c(368): error C2065: 'infbuf' : undeclared identifier
1>~\src\json_tokener.c(369): error C2065: 'infbuf' : undeclared identifier
1>~\src\json_tokener.c(369): warning C4047: 'function' : 'const char *' differs in levels of indirection from 'int'
1>~\src\json_tokener.c(369): warning C4024: 'strncmp' : different types for formal and actual parameter 2
1>~\src\json_tokener.c(374): error C2065: 'INFINITY' : undeclared identifier
1>~\src\json_tokener.c(374): error C2065: 'INFINITY' : undeclared identifier
1>~\src\json_tokener.c(411): warning C4013: 'nan' undefined; assuming extern returning int
1>  json_object.c
1>~\src\json_object.c(409): warning C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C++ conformant name: _strdup. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\string.h(238) : see declaration of 'strdup'
1>~\src\json_object.c(603): warning C4013: 'isnan' undefined; assuming extern returning int
1>~\src\json_object.c(604): warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(363) : see declaration of '_snprintf'
1>~\src\json_object.c(605): warning C4013: 'isinf' undefined; assuming extern returning int
1>~\src\json_object.c(607): warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(363) : see declaration of '_snprintf'
1>~\src\json_object.c(609): warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(363) : see declaration of '_snprintf'
1>~\src\json_object.c(611): warning C4996: '_snprintf': This function or variable may be unsafe. Consider using _snprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\stdio.h(363) : see declaration of '_snprintf'
1>~\src\json_object.c(649): error C2143: syntax error : missing ';' before 'type'
1>~\src\json_object.c(650): error C2065: 'new_ds' : undeclared identifier
1>~\src\json_object.c(657): error C2065: 'new_ds' : undeclared identifier
1>~\src\json_object.c(657): warning C4022: 'json_object_set_serializer' : pointer mismatch for actual parameter 3
1>~\src\json_object.c(684): warning C4244: 'return' : conversion from 'int64_t' to 'double', possible loss of data
1>  debug.c
1>  arraylist.c
1>  Generating Code...
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by Nzbuu** [comment]
Looks like `JSON_C_HAVE_INTTYPES_H` is defined in both config.h.win32 and json_config.h.win32. Seems like a good idea to only define it once.

Note that VS2010 does not include inttypes.h, but it does include stdint.h. This appears to be the origin of some of the errors.

**Comment by sixlettervariables** [comment]
@Nzbuu, I'd have to run this by Michael but perhaps one solution is to include Alexander Chemeris' inttypes and stdint libraries?

https://code.google.com/p/msinttypes/source/browse/#svn%2Ftrunk

**Comment by Nzbuu** [comment]
@sixlettervariables, I've raised a PR against your branch (https://github.com/sixlettervariables/json-c/pull/1). Seems to build successfully in all these cases.

The crux was that I had to force it to compile as C++ (/TP flag).

**Pull request merged**
