### PR TITLE
Add uninstall target in cmake

### PR DESCRIPTION
**Pull request by dota17**
Add uninstall target in cmake

### CODE REVIEW

**Comment by dota17** [comment]
hi, hawicz
I have added several cmake features before. What else do you think needs to be added in cmake?

**Comment by hawicz** [comment]
er... that's odd, I could have sworn I had commented on this change.
Anyway: using the -r option to rm is unnecessary and dangerous.  The contents of install_manifest.txt look like it's just files, not directories, and even if it were directories you wouldn't want to remove them if they happened to contain non-json-c files in them.

**Comment by dota17** [comment]
I have modified the make_uninstall in CMakeLists.txt and added the cmake/cmake_uninstall.cmake.in file according the [official manual](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake)

**Comment by hawicz** [comment]
oof, that's a whole pile of complexity for a marginally useful feature.  :(  Sure, they might recommend that for "cross platform compatibility", but let's not drink _all_ the kool aid.
Please feed the contents of install_manifest to rm like you were doing before, just without the "-r" option to recurse.

**Comment by dota17** [comment]
ok, finished

**Pull request merged**
