### PR TITLE
Adding JSON_C_TO_STRING_PRETTY_TAB flag

### PR DESCRIPTION
**Pull request by haata**
- Tabs are easier to read for tired eyes and editor adjustable

### CODE REVIEW

**Comment by hawicz** [comment]
This could be simpler by having JSON_C_TO_STRING_PRETTY_TAB be a modifier of JSON_C_STRING_PRETTY.  It *is* defined as a flag after all, and could simply be or'd together.

**Comment by haata** [comment]
I'd defined it as another bit. Would you prefer another argument instead for specialization?

**Comment by hawicz** [comment]
No, I'm saying you can avoid most of the modifications to the code if you actually use it as a flag to augment JSON_C_STRING_PRETTY.  i.e.

    res = json_object_to_json_string_ext(jso, JSON_C_STRING_PRETTY|JSON_C_STRING_PRETTY_TAB)

**Comment by haata** [comment]
@hawicz 
Sorry about the delay, work had me tied up.

Ah, yep, makes perfect sense. Updating the commit.

**Pull request merged**
