### PR TITLE
add the list of issues& prs closed

### PR DESCRIPTION
**Pull request by dota17**

### CODE REVIEW

**Comment by dota17** [comment]
···
since commit d582d3(2017-12-07) to 31f1ab(2020-04-03)
···
@hawicz Is this correct?

**Comment by hawicz** [comment]
No, the ending commit should be the most recent one on the master branch.  We're not using 4/3 as a cutoff for the release, that's just what happened to be current at the time that I was filling in that part of the notes wiki page.

**Comment by dota17** [comment]
@hawicz done.
https://github.com/dota17/json-c/blob/list_closed_issue_pr/issues_closed_for_0.14.md

**Comment by hawicz** [comment]
Thanks!

**Pull request merged**
